// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: token_validation_message.proto

package protobuf_token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenValidationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenValidationRequest) Reset() {
	*x = TokenValidationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_validation_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationRequest) ProtoMessage() {}

func (x *TokenValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationRequest.ProtoReflect.Descriptor instead.
func (*TokenValidationRequest) Descriptor() ([]byte, []int) {
	return file_token_validation_message_proto_rawDescGZIP(), []int{0}
}

func (x *TokenValidationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenValidationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    bool   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *TokenValidationResponse) Reset() {
	*x = TokenValidationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_validation_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationResponse) ProtoMessage() {}

func (x *TokenValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationResponse.ProtoReflect.Descriptor instead.
func (*TokenValidationResponse) Descriptor() ([]byte, []int) {
	return file_token_validation_message_proto_rawDescGZIP(), []int{1}
}

func (x *TokenValidationResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *TokenValidationResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_token_validation_message_proto protoreflect.FileDescriptor

var file_token_validation_message_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2e, 0x0a, 0x16, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4b, 0x0a, 0x17, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x32, 0x68, 0x0a, 0x16, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e,
	0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1d, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token_validation_message_proto_rawDescOnce sync.Once
	file_token_validation_message_proto_rawDescData = file_token_validation_message_proto_rawDesc
)

func file_token_validation_message_proto_rawDescGZIP() []byte {
	file_token_validation_message_proto_rawDescOnce.Do(func() {
		file_token_validation_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_validation_message_proto_rawDescData)
	})
	return file_token_validation_message_proto_rawDescData
}

var file_token_validation_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_token_validation_message_proto_goTypes = []interface{}{
	(*TokenValidationRequest)(nil),  // 0: token.TokenValidationRequest
	(*TokenValidationResponse)(nil), // 1: token.TokenValidationResponse
}
var file_token_validation_message_proto_depIdxs = []int32{
	0, // 0: token.TokenValidationService.ValidateToken:input_type -> token.TokenValidationRequest
	1, // 1: token.TokenValidationService.ValidateToken:output_type -> token.TokenValidationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_validation_message_proto_init() }
func file_token_validation_message_proto_init() {
	if File_token_validation_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token_validation_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenValidationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_validation_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenValidationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_validation_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_validation_message_proto_goTypes,
		DependencyIndexes: file_token_validation_message_proto_depIdxs,
		MessageInfos:      file_token_validation_message_proto_msgTypes,
	}.Build()
	File_token_validation_message_proto = out.File
	file_token_validation_message_proto_rawDesc = nil
	file_token_validation_message_proto_goTypes = nil
	file_token_validation_message_proto_depIdxs = nil
}
